ci:
    autoupdate_schedule: quarterly
repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
  - id: nbqa-pyupgrade
    files: ^examples
    args:
    - --py38-plus
  - id: nbqa-isort
    files: ^examples
- repo: https://github.com/kynan/nbstripout
  rev: 0.9.1
  hooks:
  - id: nbstripout
    files: ^examples
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.13
  hooks:
    - id: ruff-check
      args: ["--fix"]
    - id: ruff-format
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.21.2
  hooks:
    - id: pyproject-fmt
